services:
  next-app:
    build:
      context: .
      target: next
    environment:
      - NODE_ENV=development
    ports:
      - "80:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]