on: [push]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm audit --audit-level=high

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome', 'edge']
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          install: true
          start: npm run dev
          browser: ${{ matrix.browser }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos
          retention-days: 5
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          retention-days: 5

  build-push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build and push Docker image
#        run: |
#          docker build -t ghcr.io/${{ github.repository }}/next-app:latest .
#          docker push ghcr.io/${{ github.repository }}/next-app:latest

      - name: Build and push Docker image with docker action
        uses: docker/build-push-action@v6
        with:
          context: .
          target: next
          push: true
          tags: ghcr.io/${{ github.repository }}/next-app:${{ github.ref_name }}

  deploy-prod:
    needs: build-push
    uses: alexispe/next-cda241/.github/workflows/deploy.yml@main
    with:
      env: prod
      branch: main
      url: http://ec2-51-44-233-51.eu-west-3.compute.amazonaws.com
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-test:
    needs: build-push
    uses: alexispe/next-cda241/.github/workflows/deploy.yml@main
    with:
      env: test
      branch: develop
      url: http://ec2-51-44-233-51.eu-west-3.compute.amazonaws.com:8080
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

