on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - run: npm run e2e:headless
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos