on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build and push Docker image
#        run: |
#          docker build -t ghcr.io/${{ github.repository }}/next-app:latest .
#          docker push ghcr.io/${{ github.repository }}/next-app:latest

      - name: Build and push Docker image with docker action
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/next-app:${{ github.ref_name }}

  deploy-prod:
    uses: ${{ github.repository }}/.github/workflows/reusable/deploy.yml@main
    with:
      env: prod
      branch: main
      url: http://ec2-51-44-233-51.eu-west-3.compute.amazonaws.com


  deploy-test:
    uses: ${{ github.repository }}/.github/workflows/reusable/deploy.yml@main
    with:
      env: test
      branch: develop
      url: http://ec2-51-44-233-51.eu-west-3.compute.amazonaws.com:8080


