on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - run: ls -lah
      - uses: actions/checkout@v4
      - run: ls -lah
      - run: |
          npm install
          npm run build
      - run: npm run e2e:headless